<a href="https://colab.research.google.com/github/Sachinsharma01/DemoRepo/blob/main/Copy_of_Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DCS Assignment 3

In [3]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])  # 1-D array
arr1 = np.array([[1,2,3,4,5,],[5,6,9,8,7]])  # 2-D array
arr2 = np.array([[1,2,3,4,5,],[5,6,9,8,7],[10,11,12,13,14,15]])  # 3-D array

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
# Shape
print(arr.shape)
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 5)
(3,)


In [ ]:
# Number of Dimension
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
1


In [ ]:
# Data type
# Shape
print(arr.dtype)
print(arr1.dtype)
print(arr2.dtype)

int64
int64
object


In [ ]:
# Size
# Shape
print(arr.size)
print(arr1.size)
print(arr2.size)

5
10
3


In [ ]:
import pandas as pd

In [ ]:
d = {'Column1' : arr, 'Column2' : arr1[0], 'Column3' : arr2[0]}
dataFrame = pd.DataFrame(data=d)
print(dataFrame)

   Column1  Column2  Column3
0        1        1        1
1        2        2        2
2        3        3        3
3        4        4        4
4        5        5        5


In [ ]:
arr3 =np.ones((10,2))
print(arr3)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr4 = np.zeros((7,2,3))
print(arr4)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
arr5 = np.arange(start=0,stop=100,step=3)
print(arr5)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
arr6 = np.random.randint(10,size=(7,2))
print(arr6)

[[0 4]
 [8 3]
 [5 1]
 [7 3]
 [5 0]
 [5 0]
 [7 6]]


In [ ]:
arr7 = np.random.uniform(low=0,high=1,size=(3,5))
print(arr7)

[[0.99978276 0.26840177 0.81464405 0.38651723 0.24104543]
 [0.11874792 0.39873138 0.27917233 0.67705842 0.90447798]
 [0.54624954 0.66694123 0.6866566  0.15055473 0.02887385]]


In [ ]:
np.random.seed(42)
arr8 = np.random.randint(10,size=(4,6))
print(arr8)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [ ]:
arr8 = np.random.randint(10,size=(3,7))
print(np.unique(arr8))

[0 1 2 4 6 7 8 9]


In [ ]:
print(arr8[0])

[8 7 4 1 4 7 9]


In [ ]:
print(arr8[0],arr8[1])

[8 7 4 1 4 7 9] [8 8 0 8 6 8 7]


In [ ]:
print(arr8[0][:2],"\n",arr8[1][:2])

[8 7] 
 [8 8]


In [6]:
a = np.random.randint(10,size=(3,5))
b = np.zeros(shape=(3,5))
c = a + b
print(a + b)

[[8. 7. 6. 1. 3.]
 [7. 7. 6. 9. 0.]
 [9. 8. 7. 8. 5.]]


In [8]:
arrOnes = np.ones((3,5))
d = c - arrOnes
print(d)

[[ 7.  6.  5.  0.  2.]
 [ 6.  6.  5.  8. -1.]
 [ 8.  7.  6.  7.  4.]]


In [10]:
arre = d * arrOnes
print(arre)

[[ 7.  6.  5.  0.  2.]
 [ 6.  6.  5.  8. -1.]
 [ 8.  7.  6.  7.  4.]]


In [11]:
arrd = arre ** 2
print(arrd)

[[49. 36. 25.  0.  4.]
 [36. 36. 25. 64.  1.]
 [64. 49. 36. 49. 16.]]


In [12]:
print(np.square(arrd))

[[2.401e+03 1.296e+03 6.250e+02 0.000e+00 1.600e+01]
 [1.296e+03 1.296e+03 6.250e+02 4.096e+03 1.000e+00]
 [4.096e+03 2.401e+03 1.296e+03 2.401e+03 2.560e+02]]


In [13]:
print(np.mean(arrd))

32.666666666666664


In [14]:
print(np.max(arrd))

64.0


In [16]:
print(np.std(arrd))

20.1582627117407


In [17]:
np.reshape(arrd,(3,5,1))

array([[[49.],
        [36.],
        [25.],
        [ 0.],
        [ 4.]],

       [[36.],
        [36.],
        [25.],
        [64.],
        [ 1.]],

       [[64.],
        [49.],
        [36.],
        [49.],
        [16.]]])

In [18]:
np.transpose(arrd)

array([[49., 36., 64.],
       [36., 36., 49.],
       [25., 25., 36.],
       [ 0., 64., 49.],
       [ 4.,  1., 16.]])

In [21]:
rarr1 = np.random.randint(10,size=(3,3))
rarr2 = np.random.randint(10,size=(3,2))
print(np.dot(rarr1,rarr2))

[[ 75 118]
 [ 81 102]
 [ 77 105]]


In [24]:
np.transpose(rarr1)
print(np.dot(rarr1,rarr2))

[[ 75 118]
 [ 81 102]
 [ 77 105]]


In [31]:
aa = np.random.randint(10,size=(3,3))
bb = np.random.randint(10,size=(3,3))
print(aa > bb)

[[ True  True False]
 [ True  True  True]
 [False  True  True]]


In [32]:
print(aa[aa > 7])

[9 9]


In [33]:
print(aa == bb)

[[False False False]
 [False False False]
 [ True False False]]


In [34]:
np.sort(aa)

array([[0, 6, 9],
       [3, 5, 9],
       [2, 5, 6]])

In [36]:
np.argsort(aa)

array([[2, 1, 0],
       [0, 1, 2],
       [0, 2, 1]])

In [39]:
print(np.argwhere(aa == np.max(aa)))
print(np.argwhere(aa == np.min(aa)))

[[0 0]
 [1 2]]
[[0 2]]


In [40]:
print(np.argmax(aa,axis=1))
print(np.argmin(aa,axis=0))

[0 2 1]
[2 1 0]


In [47]:
r = np.random.normal(5,5,size=(3,3))
print(r)

[[ 6.13272622 -3.92339226 12.2607805 ]
 [16.75271383  1.93122768  7.80183237]
 [ 4.85015014  5.80267134 -3.159439  ]]


In [50]:
ar = np.linspace(1,100)
print(ar)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.510204